Update check_pr_labels.yaml

diff --git a/.github/workflows/check_pr_labels.yaml b/.github/workflows/check_pr_labels.yaml
--- a/.github/workflows/check_pr_labels.yaml
+++ b/.github/workflows/check_pr_labels.yaml
@@ -2,7 +2,7 @@ name: PR environment deployer
 
 on:
   pull_request:
-    types: [labeled, opened, edited]
+    types: [labeled]
 
 env:
   REPOSITORY: "ruby-apps-deploy"
@@ -12,7 +12,7 @@ env:
 jobs:
   build:
     name: Pull request environment deployer
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
       - uses: actions/checkout@v2.0.0
       
@@ -59,7 +59,7 @@ jobs:
           echo "EKS_SERVICE=${{secrets.EKS_SERVICE}}" >> $GITHUB_ENV
     
       #Comment if it has to be run on a public Agent 
-      - name: (GLOBAL) Configure AWS credentials using the secrets obtained from Vault
+      - name: (GLOBAL) Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
@@ -102,10 +102,10 @@ jobs:
       - name: Check if a valid Environment is set and deploy the pr image
         env:
           LABELS: ${{ toJson(github.event.pull_request.labels) }}
+          PULL_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
           ECR_REPO: 425300134585.dkr.ecr.us-west-1.amazonaws.com
         run: |
-          #if jq --exit-status 'any(test("QA1") or test("QA2") or test("QA3") or test("QA4") or test("QA5") or test("QA6"))' >/dev/null <<< $LABELS; then
-          #echo $LABELS
+          if jq --exit-status 'any(test("QA1") or test("QA2") or test("QA3") or test("QA4") or test("QA5") or test("QA6"))' >/dev/null <<< $PULL_LABELS; then
           POSSIBLE_ENVS="QA1 QA2 QA3 QA4 QA5 QA6 "
           for LABEL in $(echo $LABELS | jq -r '.[].name'); do
             if [[ $POSSIBLE_ENVS =~ (^|[[:space:]])$LABEL($|[[:space:]]) ]]; then
@@ -125,13 +125,18 @@ jobs:
             echo "Updating PR image on the following environments"
             echo $VAL
             echo "==================================================================================="
-            VAL=$(echo $VAL | tr '[:upper:]' '[:lower:]')
-            sed -i -e "s|image:.*|image: $ECR_REPO/${EKS_SERVICE}:$COMMIT|g" helm/$VAL/values.yaml
-            git add helm/$VAL/values.yaml
+            VAL=$(echo $VAL | tr '[:upper:]' '[:lower:]' | sed 's,",,g')
+            if [ -f "helm/$VAL/${EKS_SERVICE}/values.yaml" ]; then
+              #cat helm/$VAL/${EKS_SERVICE}/values.yaml
+              sed -i -e "s|image:.*|image: $ECR_REPO/${EKS_SERVICE}:$COMMIT|g" helm/$VAL/${EKS_SERVICE}/values.yaml
+              #cat helm/$VAL/${EKS_SERVICE}/values.yaml
+              git add helm/$VAL/${EKS_SERVICE}/values.yaml
+            fi
           done  
 
           git commit -m "Update ${EKS_SERVICE} image to ${COMMIT} on deploy folder/s $VALUES"
           set +e
+          git status
           git push origin master > error 
           cat error
           if [[ $(cat error | grep -c "error" ) -eq 1 ]]; then
@@ -143,11 +148,12 @@ jobs:
             git pull
             git commit -m "Update ${EKS_SERVICE} image to ${COMMIT} on deploy folder/s $VALUES"
             git push origin master
-            
-          #else
-            #echo $LABELS
-            #echo "::error ::Please set environment/ENVIRONMENT_NAME as label"
-          #fi
+          fi  
+          else
+            echo $LABELS
+            echo "::error ::Please set a valid env name as a label"
+            exit 1
+          fi
 
       - name: Checkout code
         uses: actions/checkout@v2
